spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activitidemo?characterEncoding=utf-8
    username: root
    password: 123456
    type: com.mchange.v2.c3p0.ComboPooledDataSource
mybatis:
  type-aliases-package: believep.pojo
pagehelper:
  helper-dialect: mysql